### PR TITLE
Added a way to optionally specific a list of favorite channels

### PR DESCRIPTION
**Pull request by phillipgreenii**
I loved your script, but I don't want all 300 channels.  I want to be able to specify (via slug) which channels i want to download.  This patch allows for that.

### CODE REVIEW

**Comment by evoactivity** [comment]
lgtm

**Comment by phillipgreenii** [comment]
Thank you for the quick review!

**Comment by phillipgreenii** [comment]
@evoactivity thanks again for the quick merge.  Can you also publish the latest version to npm?

**Comment by evoactivity** [comment]
Sorry @phillipgreenii been crazy busy, quick to merge, slow to release lol. I've just published the latest version now though. Thanks for the contribution :)

**Comment by phillipgreenii** [comment]
@evoactivity no problem. Thank you!

**Pull request merged**
